### ISSUE TITLE
help with development cycle

### ISSUE THREAD

**Issue by cornhundred** [ajduberstein/pydeck_custom_layer#4]
Hi, I am using this template to make a custom pydeck layer here https://github.com/cornhundred/pydeck-lasso-layer. I was able to add a [console log](https://github.com/cornhundred/pydeck-lasso-layer/blob/master/labeled-geojson-layer.js#L3) statement to the JavaScript bundle, publish, and re-run the notebook [check_custom_layer.ipynb](https://github.com/cornhundred/pydeck-lasso-layer/blob/master/check_custom_layer.ipynb) and I see the new console log statement. But, is there a quicker way to check the custom layer without having to publish to npm? For instance, for the development of our custom widget [Clustergrammer2](https://github.com/ismms-himc/clustergrammer2) I run `webpack --watch` and am able to refresh the notebook page to bring up the latest JavaScript build.

For background - I am trying to make a polygon/lasso selection layer using nebula.gl (see https://github.com/visgl/deck.gl/issues/5122) and trying to try to follow this [example in codesandbox](https://codesandbox.io/s/deckgl-and-nebulagl-editablegeojsonlayer-no-react-forked-7fcst?file=/app.js) (I'm also trying to get this example working on [Observablehq](https://observablehq.com/@cornhundred/lasso-selection) but am running into [issues requiring](https://talk.observablehq.com/t/issue-requiring-nebula-gl/4153) the library).

**Comment by cornhundred** [comment]
Update on the Observable end - I was able to import nebula.gl and deck.gl into this notebook https://observablehq.com/@cornhundred/lasso-selection but I'm unable to get the nebula editable layer to render (I could not find out how to get `DrawPolygonMode` from nebula.gl). I'm trying to reproduce the example from https://codesandbox.io/s/deckgl-and-nebulagl-editablegeojsonlayer-no-react-forked-l0n65?file=/app.js:153-160

**Comment by ajduberstein** [comment]
I've updated the repo with more comments. I'd recommend using the webpack cli to serve the JS bundle, and then use the URL for that JS bundle in the custom libraries dictionary within pydeck.

I've never tried to get Nebula working on Observable, but based on the number of deck.gl examples that are hosted there, I'd believe it should work.

**Comment by cornhundred** [comment]
Thanks @ajduberstein, that worked. I made a new repo using the updated template and am now able to update `labeled-geojson-layer.js` and immediately see the update on Jupyter. 

Now, I'll try to get nebula selection layer to work :)
