### ISSUE TITLE
error importing nebula in custom layer

### ISSUE THREAD

**Issue by cornhundred** [ajduberstein/pydeck_custom_layer#7]
Hi, 

I'm trying to import nebula to make a selection layer for PyDeck (trying to follow this [code sandbox example](https://codesandbox.io/s/deckgl-and-nebulagl-editablegeojsonlayer-no-react-forked-7fcst?file=/app.js)). However, I'm getting an error in the console 

<img width="689" alt="Screen Shot 2020-11-16 at 11 45 58 PM" src="https://user-images.githubusercontent.com/8352840/99347846-15a76800-2866-11eb-9193-87dc19f70c47.png">

when I try to [import nebula](https://github.com/cornhundred/nebula_select_layer/blob/master/labeled-geojson-layer.js#L5)

```
import { EditableGeoJsonLayer, DrawPolygonMode } from 'nebula.gl';
```

Yarn and webpack appear to build correctly.

I can raise this issue in the nebula repo if this is out of scope of this repo.

**Comment by cornhundred** [comment]
Here is a link to the repo and place where nebula.gl is being imported 

https://github.com/cornhundred/nebula_select_layer/blob/master/labeled-geojson-layer.js#L5

**Comment by ajduberstein** [comment]
Let me ask some others on the vis.gl team why you're getting this result–it looks like a bundling issue. Give me a day and I'll update the issue.

**Comment by cornhundred** [comment]
@ajduberstein thank you I appreciate all the help!

**Comment by ajduberstein** [comment]
Unfortunately no leads here yet. I’ll try implementing this myself.

**Comment by cornhundred** [comment]
@ajduberstein thanks! I'll try troubleshooting more as well
